/**
 * @File Name          : CampaignMemberHandler.cls
 * @Description        : 
 * @Author             : Saranya
 * @Group              : 
 * @Last Modified By   : Saranya
 * @Last Modified On   : 9/11/2019, 10:35:52 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    9/11/2019   Saranya     Initial Version
**/
public with sharing class CampaignMemberHandler 
{
   
/* This Method checks for Leads on CampaignMember Insertion on same time range */
    public static void OnBeforeInsert(List<CampaignMember> campaignMemberObjList)
    {
       
    }


}